import { test, expect } from '@playwright/test';

test('Demo test example', async ({ page }) => {
  await page.goto('http://www.automationpractice.pl/index.php');
  await page.getByRole('link', { name: 'T-shirts' }).first().click();
  await page.getByRole('checkbox', { name: 'S (1)' }).check();
  await page.goto('http://www.automationpractice.pl/index.php?id_category=5&controller=category#/size-s');
  await page.getByLabel('Sort by').selectOption('price:asc');
  await page.goto('http://www.automationpractice.pl/index.php?id_category=5&controller=category&orderby=price&orderway=asc&orderway=asc');
  
  await expect(page.getByRole('link', { name: 'Faded Short Sleeve T-shirts' }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Faded Short Sleeve T-shirts' }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Shop' })).toBeVisible();
  await expect(page.locator('#contact-link')).toContainText('Contact us');
  await expect(page.getByRole('navigation')).toContainText('Sign in');
  await expect(page.locator('#block_top_menu').getByRole('link', { name: 'Women' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dresses', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'T-shirts' }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Blog' })).toBeVisible();
});






































// import { test, expect } from '@playwright/test';


// test('Test generated by Playwright', async ({ page }) => {
//   const texts = {
//     playwrightLogo: 'Playwright logo Playwright',
//     docsTab: 'Docs',
//   };

//   await page.goto('https://playwright.dev/');
//   await expect(page.getByRole('link', { name: texts.playwrightLogo })).toBeVisible();
//   await expect(page.getByRole('link', { name: texts.docsTab })).toBeVisible();
//   await expect(page.getByRole('link', { name: 'API' })).toBeVisible();
//   await expect(page.getByRole('button', { name: 'Node.js' })).toBeVisible();
//   await expect(page.getByRole('link', { name: 'Community' })).toBeVisible();

//   await page.getByRole('link', { name: 'Get started' }).click();
//   await page.getByRole('link', { name: 'Generating tests' }).click();
//   await expect(page.locator('h1')).toContainText('Generating tests');
// });


// test.skip('has title', async ({ page }) => {
//   await page.goto('https://playwright.dev/');

//   // Expect a title "to contain" a substring.
//   await expect(page).toHaveTitle(/Playwright/);
// });



// test.skip('get started link', async ({ page }) => {
//   await page.goto('https://playwright.dev/');

//   // Click the get started link.
//   await page.getByRole('link', { name: 'Get started' }).click();

//   // Expects page to have a heading with the name of Installation.
//   await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
// });
